Exercise 10
robin-leach/DevOps-Course pull request #11
Opened 2021-03-20 12:34 UTC by robin-leach

2021-03-25 09:43 UTC, hugh-emerson commented on Dockerfile
> +RUN pip install gunicorn flask pymongo[srv] flask_login oauthlib
So first of all, you're running `gunicorn` directly rather than `poetry run gunicorn`, so it needs globally installed gunicorn and then everything else too. It's not using the poetry virtual env.

Buuut even after you do that you may find it works locally and not in Heroku.
You can run this just before poetry install: `poetry config virtualenvs.create false --local` so that it does install things globally. There's just some undocumented weirdness with how Heroku runs containers.

2021-03-31 15:37 UTC, JackMead requested changes
Looks good, I've left a couple of minor comments below (and see Hugh's response re the dockerfile) but the primary change I'd recommend is that we should have some documentation in our README for the OAuth setup required, e.g. setting it up in github and setting the relevant environment variables.

Also, not a change in this review, but your prod docker-compose no longer runs; it should have a default PORT environment variable set (e.g. in the Dockerfile or directly in docker-compose.yml)

2021-03-31 15:37 UTC, JackMead commented on app.py
> +    app.secret_key = os.urandom(24)
Using this randomly generated does mean that your sessions are being cycled every time the app comes up - that's fine here, but worth noting that if we had the app being served from multiple servers, the user would be tied to an individual server instance

2021-03-31 15:37 UTC, JackMead commented on app.py
> +        if login_success:
Worth noting that if this fails, the user will just see an error since we don't return anything

2021-03-31 15:37 UTC, JackMead commented on app.py
> +        user = User(current_user.get_id())
Here, current_user is already an instance of your `User` model - loaded by the load_user function you had to define - so this is the same as:
```
user = current_user
```

2021-03-31 15:37 UTC, JackMead commented on app.py
> +        else:
Nice. If we wanted to extend this to more routes, I'd encourage converting to a decorator, so that we can easily reuse the code, but happy here

2021-04-01 13:15 UTC, robin-leach commented on Dockerfile
> +RUN pip install gunicorn flask pymongo[srv] flask_login oauthlib
oh my gosh 🤦 Thank you so much, I had been so confused about this!

2021-04-01 13:32 UTC, robin-leach commented on app.py
> +        user = User(current_user.get_id())
Yeah, the main reason I did this was because the IDE doesn't seem to be smart enough to know that, and so doing this seemed to be the easiest way of convincing it that we had a `User` and that you can call `get_role` etc.

2021-04-01 13:34 UTC, robin-leach commented on app.py
> +    app.secret_key = os.urandom(24)
Interesting point! I guess then you would just need to generate a secret key once and then store it an an env variable?

2021-04-06 06:53 UTC, hugh-emerson commented on app.py
> +        user = User(current_user.get_id())
So you are calling .get_id() on this line in order to get the IDE to know you can call .get_role() on the next line?

What you want is simply `current_user: User`

2021-04-06 16:26 UTC, robin-leach commented on app.py
> +        user = User(current_user.get_id())
Oh yeah, that's much better, thanks!

2021-04-14 13:22 UTC, hugh-emerson approved these changes
Looks good! Merge when you're ready 👍

2021-04-14 13:22 UTC, hugh-emerson commented on README.md
> + The app must linked to a Github OAuth app, through the `CLIENT_ID` and `CLIENT_SECRET` env variables. Either obtain these from an existing Github OAuth app, or follow [these instructions](https://do
You should mention what the callback route is.

2021-04-14 13:44 UTC, merged