Exercise 3
robin-leach/DevOps-Course pull request #3
Opened 2020-07-21 15:41 UTC by robin-leach

I wasn't able to finish this exercise. I got up to starting the selenium setup, but despite my best efforts I couldn't get the environment variables to load properly in the test app, and so couldn't get the end to end tests to work.

2020-07-29 15:11 UTC, Jonesey13 commented on e2e_tests/end_to_end_test.py
> +    yield app
Undefined variable (do you mean `application`?)

2020-07-29 15:12 UTC, Jonesey13 commented on helpers/index_test.py
> +import pytest
Not added to `requirements.txt`

2020-07-29 15:12 UTC, Jonesey13 commented on helpers/index_test.py
> +from freezegun import freeze_time
Not added to `requirements.txt`

2020-07-29 15:13 UTC, Jonesey13 commented on test_app.py
> +    file_path = find_dotenv('test_env_file')
You'll want `find_dotenv('test_env_file.txt')` although this will clash with the e2e test run

2020-07-30 14:53 UTC, robin-leach commented on test_app.py
> +    file_path = find_dotenv('test_env_file')
Why will it clash?

2020-08-19 23:13 UTC, hugh-emerson requested changes
See my comments for an explanation of what's going wrong. Let me know via Slack or book a 1-to-1 if you still can't get the tests working.

2020-08-19 23:13 UTC, hugh-emerson commented on .gitignore
> +geckodriver.exe
Good to gitignore this but adding things to gitignore won't actually remove them from the repo if they were already being tracked. You need to delete the geckodriver.exe file from the repo yourself.

2020-08-19 23:13 UTC, hugh-emerson commented on README.md
> +To run end-to-end tests, run `python -m pytest e2e_tests/end_to_end_test.py`
You should also mention the prerequisites - geckodriver.exe (once you delete it from the repo) and Firefox

2020-08-19 23:13 UTC, hugh-emerson commented on README.md
> +To run all tests, run `python -m pytest`
Is there any reason to run `python -m pytest` rather than just `pytest`?

2020-08-24 20:33 UTC, hugh-emerson commented
Markups look good to me :+1: Merge away!

2020-08-25 08:16 UTC, merged