Exercise 4
robin-leach/DevOps-Course pull request #5
Opened 2020-08-13 16:03 UTC by robin-leach

2020-08-14 14:08 UTC, robin-leach commented on bootstrap.sh
> +#!/usr/bin/env bash
Oh i meant to get rid of this, i moved it all to inline shell...

2020-08-24 11:50 UTC, Jonesey13 commented on Vagrantfile
> +      poetry run flask run --host 0.0.0.0
This will hang the vagrant script until the flask server fatally crashes. This also blocks the use of commands like vagrant destroy.

I'd advise using 
`nohup poetry flask run --host 0.0.0.0 &` 
to make this run a background thread or move over to using `gunicorn --daemon`

This probably blocks me from passing this submission.

2020-08-27 22:52 UTC, hugh-emerson requested changes
I'm afraid your small markups have broken your Vagrantfile. At least when I tried running it.

See my other comments for details.

In addition, it would be good to mention vagrant in the README

2020-08-27 22:52 UTC, hugh-emerson commented on Vagrantfile
> +    echo 'export PYENV_ROOT="~/.pyenv"' >> ~/.profile
I'm afraid your markups have broken this. The tilde doesn't get expanded when inside quotes.
You want `"$HOME/.pyenv"` or `~/.pyenv` (no quotes). What you've got is setting PYENV_ROOT to exactly `~/.pyenv` rather than `/home/vagrant/.pyenv`. So PATH contains `~/.pyenv/bin` instead of `/home/vagrant/.pyenv/bin` and it breaks such that `pyenv install` doesn't work.

See for yourself with vagrant destroy and then vagrant up a new VM.

2020-08-27 22:52 UTC, hugh-emerson commented on Vagrantfile
> +      nohup poetry run flask run --host 0.0.0.0 &
Does this work for you? You can access localhost:5000 after simply running vagrant up?

I find I need to redirect the output for the process to continue running (which shouldn't normally be the case in bash but maybe vagrant doesn't like the default nohup behaviour of nohup.out)

2020-08-28 11:01 UTC, robin-leach commented on Vagrantfile
> +    echo 'export PYENV_ROOT="~/.pyenv"' >> ~/.profile
Unfortunately none of this works for me any more. Despite working when I first submitted it, and despite the fact that I had changed nothing when I came to do the review markups, I suddenly started getting errors along the lines of:
```
RuntimeError: Hashes for poetry-1.0.10-linux.tar.gz do not match: b5a5441f9714e21eaffec3d67ffeaa81d5df5cc232efffce8d06b8f56599c0e9 != 827275673e6d9acbe994074374bbc77290ef19e2ec57a6e521f9edfa209bf42f
```
It seems that Tim and Oskar also have had this and haven't been able to find any way of solving it, as far as I am aware.

Do you have any idea what this is or how to fix it?

2020-08-28 12:40 UTC, hugh-emerson commented on Vagrantfile
> +    echo 'export PYENV_ROOT="~/.pyenv"' >> ~/.profile
Ah, I haven't had this myself but some people had checksum errors similar to this when using virtual box if they had either of these Windows features turned on - "Hyper-V" or "Virtual Machine Platform". So make sure those are off.

It may be specific to a particular version of virtualbox so if that doesn't solve it, you could try an older one, say 6.1.0 (though I'm on the latest)

If you've been discussing it with them already, are you okay to pass the message on? And please let me know whether this fixes it.

2020-09-05 15:49 UTC, robin-leach commented on Vagrantfile
> +    echo 'export PYENV_ROOT="~/.pyenv"' >> ~/.profile
Okay I cannot explain why, but it is now working again, without me changing anything as far as I can tell!

2020-09-05 16:07 UTC, robin-leach commented on Vagrantfile
> +      nohup poetry run flask run --host 0.0.0.0 &
Ah right you are - redirecting the output seems to fix it.

2020-09-07 12:49 UTC, hugh-emerson approved these changes
Looks good. I've left some comments around poetry/the README, but go ahead and merge when you're ready.

2020-09-07 12:49 UTC, hugh-emerson commented on pyproject.toml
> +wrapt="1.11.2"
You don't need to include nested dependencies in pyproject.toml.

Also, it's nicer to put pytest/selenium etc into the dev-dependencies section below.

2020-09-07 12:49 UTC, hugh-emerson commented on README.md
> +
Good job updating the README for Vagrant, and also for switching your project from pip/venv to poetry.
But you now need to update the README to match. It still says to run setup.sh (which no longer works) and flask run (rather than poetry run flask run).

You could keep setup.sh, updated to do `poetry install` instead of the venv/pip stuff, or just delete it and add `cp .env.template ...` and `poetry install` to the README.

2020-09-07 13:31 UTC, merged