Exercise 5: Immutable Infrastructure
robin-leach/DevOps-Course pull request #6
Opened 2020-09-16 14:47 UTC by robin-leach

2020-09-16 14:50 UTC, robin-leach commented on Dockerfile
> +  && poetry install
I wasn't sure about having the `COPY` stage first,but then the `poetry install` command relies on the `pyproject.toml` file having been copied across 🤔

2020-09-18 16:26 UTC, Jonesey13 requested changes
Very nearly there! This is essentially a pass (modulo a small fix to the docker compose version).

Please apply this small change and then merge in the PR 👍

2020-09-18 16:26 UTC, Jonesey13 commented on Dockerfile
> +  && poetry install
I'd be tempted to split this into 2 `RUN` steps with the copy command in the middle. This means you don't have to install poetry every time you update/add a dependency.

2020-09-18 16:26 UTC, Jonesey13 commented on docker-compose.yml
> +version: "3"
I get an error with this version saying that `target` is unrecognised. Had to update this to 3.8 to get it working:
```suggestion
version: "3.8"
```

2020-09-18 16:34 UTC, robin-leach commented on docker-compose.yml
> +version: "3"
Interesting - it worked for me. Updating regardless!

2020-09-22 14:06 UTC, merged